version: '3'

services:
  hadoop-namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HADOOP_ROLE=namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop-network

  hadoop-datanode:
    image: apache/hadoop:3.4.1
    container_name: datanode
    hostname: datanode
    ports:
      - "50075:50075"
    environment:
      - HADOOP_ROLE=datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode
    networks:
      - hadoop-network

  hive-metastore:
    image: apache/hive:4.0.1
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
      - "9083:9083"
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - HADOOP_NAMENODE_URI=hdfs://namenode:9000
    depends_on:
      - hadoop-namenode
      - hadoop-datanode
    networks:
      - hadoop-network

  hive-server:
    image: apache/hive:4.0.1
    container_name: hive-server
    hostname: hive-server
    ports:
      - "10000:10000"
    environment:
      - HIVE_SERVER_HOST=hive-server
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    depends_on:
      - hive-metastore
    networks:
      - hadoop-network

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop-network:
    driver: bridge
